spring:
    data:
        mongodb:
            uri: 'mongodb://user:password@localhost:27017'
            authentication-database: admin
            database: currencyexchange
            uuid-representation: standard