scrape_configs:
    - job_name: ' HA Cloud Session Server with TLS'
      scrape_interval: 5s
      scheme: http
      tls_config:
          insecure_skip_verify: true
      metrics_path: actuator/prometheus
      static_configs:
          -   targets: [ '172.17.0.1:8083' ]
              labels:
                  group: 'neptune'
          -   targets: [ '172.17.0.1:8084' ]
              labels:
                group: 'bff'
          -   targets: [ '172.17.0.1:8085' ]
              labels:
                  group: 'cache'
          -   targets: [ '172.17.0.1:8086' ]
              labels:
                group: 'file'
      basic_auth:
          username: 'devs@ogham-stone.com'
          password: 'password'
